 <?php
/**             
 * Caminho module/${nomeModulo}/view/${nomeModulo}/${nomeTabela}/update.phtml
 */

 $title = 'Editar ${nomeTabela}';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1> <br />
<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav">
	    <li>
	        <a href="<?php echo $this->url('${nomeVariavel}', array('action'=>'create'));?>">  
	            <?php echo $this->translate('Criar novo registro') ?>
	        </a>
	    </li>
	    <li>
	        <a href="<?php echo $this->url('${nomeVariavel}', array('action'=>'delete', 'id' => $this->${nomeVariavel}}->getId()));?>">  
	            <?php echo $this->translate('Remover registro') ?>
	        </a>
	    </li>
	    <li>
	        <a href="<?php echo $this->url('${nomeVariavel}', array('action'=>'recover', 'id' => $this->${nomeVariavel}}->getId()));?>"> 
	            <?php echo $this->translate('Visualizar registro') ?>
	        </a>
	    </li>
	    <li>
	        <a href="<?php echo $this->url('${nomeVariavel}', array('action'=>'list', 'id' => $this->${nomeVariavel}->getId()));?>"> 
	            <?php echo $this->translate('Listar registros') ?>
	        </a>
	    </li>
	</ul>
</div>
<br />
<div>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'${nomeVariavel}',
		array(
			'action' => 'edit',
			'id'     => $this->${nomeVariavel}->getId()
			)
		));
	$form->prepare();
	echo $this->form()->openTag($form);
	${cpsNames}
	echo $this->formSubmit($form->get('submit')); 
	echo $this->form()->closeTag();
?>
</div>