<?php
/**             
 * Caminho module/${nomeModulo}/view/${nomeModulo}/${nomeTabela}/delete.phtml
 */

$title = 'Apagar ${nomeTabela}';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Tem certeza que deseja apagar o registro?
</p>
<?php
$url = $this->url('${nomeVariavel}', array(
	'action' => 'delete',
	'id'     => $this->${nomeVariavel}->getId(),
	));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $${nomeVariavel}->getId(); ?>" />
			<input type="submit" name="del" value="Sim" />
			<input type="submit" name="del" value="Não" />
		</div>
	</form>